### ISSUE TITLE
Security is terrible

### ISSUE THREAD

**Issue by maxwell-fr** [Cenecia/cah#11]
Security is too lax for production.

- Critical: Nothing stops cloning or impersonation of players or owners.
- Low priority: All cards are transmitted to all players.

This is true in the mainline branches as well as ws1.

**Comment by Cenecia** [comment]
Both of these issues should be resolved now.
See these two commits

- [cah](https://github.com/Cenecia/cah/commit/e65b82b847e9abcd1218ff07ea959414b5adadb7)
- [cah_frontend](https://github.com/Cenecia/cahfrontend/commit/7ced1c4c0f2af122d4c563c25096ce5e64d7a11a)
