### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by maxwell-fr** [Cenecia/cah#35]
The code has no explicit license, and therefore is using the default creator's license (i.e., copyright maximized, contributors retain rights, etc.)

It might be good to choose one before this takes off to avoid issues.

I'd suggest the AGPL (copyleft maximalist), but something more permissive like the MPL or MIT license could work. 

[Choose A License](https://choosealicense.com/) may help.

**Comment by Cenecia** [comment]
Added ISC license.
